trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName:  sample-site
    PathtoPublish: $(build.artifactStagingDirectory)

- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: '242b1977-0318-474d-8a9e-87d65c6f536d'
    pipeline: '76'
    buildVersionToDownload: 'latestFromBranch'
    branchName: 'refs/heads/master'
    downloadType: 'specific'
    downloadPath: '$(System.ArtifactsDirectory)'
    
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'ServiceConnection_Vigneshwar'
    appType: 'webApp'
    WebAppName: 'dotnetwithdockervignesh'
    packageForLinux: '$(System.ArtifactsDirectory)/sample-site/WebApp.zip'