resources:
 pipelines:
   - pipeline: Testpipeline
     project: Triggering option
     source: SourceYamlFile
     trigger: true

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName:  sample-site
    PathtoPublish: $(build.artifactStagingDirectory)

- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: 'd3917c9e-cb2c-4f26-9647-da26b8b117a5'
    pipeline: '55'
    buildVersionToDownload: 'latest'
    downloadType: 'specific'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Vicky-Demo.V2 (7a8d40b6-7f16-48d4-ad95-56fc81f464a2)'
    appType: 'webApp'
    WebAppName: 'dotnetwithdockervignesh'
    packageForLinux: '$(System.ArtifactsDirectory)/sample-site/WebApp.zip
'